-- V2 : à exécuter dans Supabase SQL Editor après avoir sauvegardé votre schéma actuel.
-- Cette version ajoute le multi-athlètes et remplace les policies trop larges de la V1.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'athlete' check (role in ('coach','athlete')),
  created_at timestamptz not null default now()
);

create table if not exists public.coach_athletes (
  coach_id uuid not null references public.profiles(id) on delete cascade,
  athlete_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (coach_id, athlete_id),
  check (coach_id <> athlete_id)
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  workout_name text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer,
  energy_before integer,
  energy_after integer,
  difficulty integer,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.session_exercises (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.workout_sessions(id) on delete cascade,
  exercise_index integer not null,
  reps_completed integer default 0,
  notes text
);

create index if not exists idx_sessions_user_started on public.workout_sessions(user_id, started_at desc);
create index if not exists idx_session_exercises_session on public.session_exercises(session_id);

alter table public.profiles enable row level security;
alter table public.coach_athletes enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.session_exercises enable row level security;

-- Nettoyage des anciennes policies V1 qui pouvaient donner trop de visibilité aux coaches.
drop policy if exists "coach read sessions" on public.workout_sessions;
drop policy if exists "users can read own profile" on public.profiles;
drop policy if exists "users can insert own sessions" on public.workout_sessions;
drop policy if exists "users can read own sessions" on public.workout_sessions;
drop policy if exists "users can update own sessions" on public.workout_sessions;
drop policy if exists "users can insert own exercises" on public.session_exercises;
drop policy if exists "users can read own exercises" on public.session_exercises;
drop policy if exists "coach read athlete profiles" on public.profiles;
drop policy if exists "coach read assignments" on public.coach_athletes;

create policy "profile self read" on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy "coach read assigned athlete profiles" on public.profiles for select to authenticated using (
  exists (select 1 from public.coach_athletes ca where ca.coach_id=(select auth.uid()) and ca.athlete_id=profiles.id)
);

create policy "coach read own assignments" on public.coach_athletes for select to authenticated using (coach_id=(select auth.uid()));
create policy "athlete read own assignment" on public.coach_athletes for select to authenticated using (athlete_id=(select auth.uid()));

create policy "athlete read own sessions" on public.workout_sessions for select to authenticated using (user_id=(select auth.uid()));
create policy "athlete insert own sessions" on public.workout_sessions for insert to authenticated with check (user_id=(select auth.uid()));
create policy "athlete update own sessions" on public.workout_sessions for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy "coach read assigned sessions" on public.workout_sessions for select to authenticated using (
  exists (select 1 from public.coach_athletes ca where ca.coach_id=(select auth.uid()) and ca.athlete_id=workout_sessions.user_id)
);

create policy "athlete read own exercises" on public.session_exercises for select to authenticated using (
  exists (select 1 from public.workout_sessions s where s.id=session_exercises.session_id and s.user_id=(select auth.uid()))
);
create policy "athlete insert own exercises" on public.session_exercises for insert to authenticated with check (
  exists (select 1 from public.workout_sessions s where s.id=session_exercises.session_id and s.user_id=(select auth.uid()))
);
create policy "coach read assigned exercises" on public.session_exercises for select to authenticated using (
  exists (select 1 from public.workout_sessions s join public.coach_athletes ca on ca.athlete_id=s.user_id where s.id=session_exercises.session_id and ca.coach_id=(select auth.uid()))
);

-- Après création de votre compte coach dans Auth, exécutez UNE FOIS :
-- update public.profiles set role='coach', full_name='Votre nom' where id='UUID_DU_COMPTE_COACH';
