let user=null,currentSession=null,startTime=null,timerInterval=null,currentWorkout=null;
function fmtDate(d){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date(d))}
function durationText(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function renderExercises(target,w,interactive=false){target.innerHTML=w.exercises.map((e,i)=>`<article class="exercise"><img src="${e[4]}" alt="${e[0]}"><div><h3>${e[0]}</h3><p>${e[1]} séries × ${e[2]} répétitions</p><p>Repos : ${e[3]} s</p>${interactive?`<label>Répétitions réalisées<input data-ex="${i}" class="reps" type="number" min="0" value="${e[2]}"></label>`:""}</div></article>`).join("")}
function updateTimer(el){if(startTime)el.textContent=durationText(Math.floor((Date.now()-startTime.getTime())/1000))}
async function loadHistory(){const {data,error}=await supabaseClient.from("workout_sessions").select("id,started_at,ended_at,duration_seconds,difficulty,notes").eq("user_id",user.id).order("started_at",{ascending:false}).limit(12);if(error){console.error(error);return}const done=(data||[]).filter(x=>x.ended_at);document.getElementById("stats").textContent=`${done.length} séance${done.length>1?"s":""}`;document.getElementById("history").innerHTML=done.length?done.map(x=>`<div class="history-item"><div><b>${fmtDate(x.started_at)}</b><div class="muted">${x.notes||"Séance terminée"}</div></div><div><span class="status ok">✓ Terminée</span><div class="muted">${durationText(x.duration_seconds||0)}</div></div></div>`).join(""):"<p class=\"muted\">Aucune séance enregistrée pour le moment.</p>"}
async function init(){user=await requireUser();if(!user)return;const {data:profile}=await supabaseClient.from("profiles").select("full_name").eq("id",user.id).single();document.getElementById("greeting").textContent=`Bonjour ${profile?.full_name||""} 👋`;document.getElementById("today").textContent=fmtDate(new Date());currentWorkout=getTodayWorkout();document.getElementById("workoutTitle").textContent=currentWorkout.title;document.getElementById("workoutDesc").textContent=currentWorkout.desc;renderExercises(document.getElementById("exerciseList"),currentWorkout);await loadHistory()}
document.getElementById("startBtn")?.addEventListener("click",async()=>{const energy=Number(document.getElementById("energyBefore").value);startTime=new Date();const {data,error}=await supabaseClient.from("workout_sessions").insert({user_id:user.id,started_at:startTime.toISOString(),energy_before:energy}).select().single();if(error){alert(error.message);return}currentSession=data;document.getElementById("activeTitle").textContent=currentWorkout.title;renderExercises(document.getElementById("activeExercises"),currentWorkout,true);document.getElementById("startView").classList.add("hidden");document.getElementById("activeView").classList.remove("hidden");timerInterval=setInterval(()=>updateTimer(document.getElementById("activeTimer")),500)});
document.getElementById("finishBtn")?.addEventListener("click",()=>{clearInterval(timerInterval);const seconds=Math.floor((Date.now()-startTime.getTime())/1000);document.getElementById("finishSummary").textContent=`Durée enregistrée : ${durationText(seconds)}.`;document.getElementById("activeView").classList.add("hidden");document.getElementById("finishView").classList.remove("hidden")});
document.getElementById("saveFinish")?.addEventListener("click",async()=>{const ended=new Date(),seconds=Math.floor((ended-startTime)/1000),difficulty=Number(document.getElementById("difficulty").value),energyAfter=Number(document.getElementById("energyAfter").value),notes=document.getElementById("notes").value.trim();const {error}=await supabaseClient.from("workout_sessions").update({ended_at:ended.toISOString(),duration_seconds:seconds,difficulty,energy_after:energyAfter,notes}).eq("id",currentSession.id);if(error){alert(error.message);return}for(const input of document.querySelectorAll(".reps")){const i=Number(input.dataset.ex),e=currentWorkout.exercises[i];await supabaseClient.from("session_exercises").insert({session_id:currentSession.id,exercise_name:e[0],sets_completed:e[1],reps_completed:Number(input.value)})}location.reload()});
init();
